version: "3.8"

services:
  app:
    container_name: inspection-app
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
