version: "3.8"

services:
  app:
    container_name: inspection-app
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - ./tmp:/app/tmp  # Ensure tmp persists and is writable
    environment:
      - PORT=3002
    restart: unless-stopped
